[package]
name = "fkl_ext_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"
async-trait = "0.1.58"

fkl-mir = { path = "../fkl_mir", version = "0.4.0" }
